// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5HW5IU_mtIl0WMUoMW1UE7wjI5hnB1ww',
    appId: '1:613211523349:web:0435898c78f30cc1bec11c',
    messagingSenderId: '613211523349',
    projectId: 'flutterfirst-d05c8',
    authDomain: 'flutterfirst-d05c8.firebaseapp.com',
    storageBucket: 'flutterfirst-d05c8.appspot.com',
    measurementId: 'G-RXXC3M56H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Abkq8zwbb33TfS4ma8Lx_wQELwiqPQI',
    appId: '1:613211523349:android:8424951fa4372d8ebec11c',
    messagingSenderId: '613211523349',
    projectId: 'flutterfirst-d05c8',
    storageBucket: 'flutterfirst-d05c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU1Vf7QZ7cKP3ZsD1IYlO_4o_tenm81BE',
    appId: '1:613211523349:ios:ca51d5f5dbbf4ca7bec11c',
    messagingSenderId: '613211523349',
    projectId: 'flutterfirst-d05c8',
    storageBucket: 'flutterfirst-d05c8.appspot.com',
    iosBundleId: 'com.example.flutterfirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU1Vf7QZ7cKP3ZsD1IYlO_4o_tenm81BE',
    appId: '1:613211523349:ios:ca51d5f5dbbf4ca7bec11c',
    messagingSenderId: '613211523349',
    projectId: 'flutterfirst-d05c8',
    storageBucket: 'flutterfirst-d05c8.appspot.com',
    iosBundleId: 'com.example.flutterfirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5HW5IU_mtIl0WMUoMW1UE7wjI5hnB1ww',
    appId: '1:613211523349:web:7b918e88ae559b4abec11c',
    messagingSenderId: '613211523349',
    projectId: 'flutterfirst-d05c8',
    authDomain: 'flutterfirst-d05c8.firebaseapp.com',
    storageBucket: 'flutterfirst-d05c8.appspot.com',
    measurementId: 'G-7YZJ7KPGJS',
  );

}